config/routes.rb
CoolRSSJobApp::Application.routes.draw do
  resources :jobs

  get "main/welcome"

  get "main/index"

  get "jobs/index"
  
  match '/jobsearch', :to => 'main#welcome'
  match '/sources',   :to => 'jobs#index'
  match '/main/links',   :to => 'main#links'

end

app/models/job.rb
class Job < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @jobs }
    end
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
    @job = Job.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @job }
    end
  end

  # GET /jobs/new
  # GET /jobs/new.json
  def new
    @job = Job.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @job }
    end
  end

  # GET /jobs/1/edit
  def edit
    @job = Job.find(params[:id])
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(params[:job])

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render json: @job, status: :created, location: @job }
      else
        format.html { render action: "new" }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /jobs/1
  # PUT /jobs/1.json
  def update
    @job = Job.find(params[:id])

    respond_to do |format|
      if @job.update_attributes(params[:job])
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job = Job.find(params[:id])
    @job.destroy

    respond_to do |format|
      format.html { redirect_to jobs_url }
      format.json { head :ok }
    end
  end
end

app/controllers/main_controller.rb
require 'rubygems'
require 'rss'
	# Allows open to access remote files
require 'open-uri'

class MainController < ApplicationController

  # GET /jobs
  # GET /jobs.json
  def welcome
	puts "in welcome"
	

	# What feed are we parsing?
	rss_feed = "http://www.careerbuilder.com/RTQ/rss20.aspx?rssid=RSS_PD&num=25&geoip=false&ddcompany=false&ddtitle=false&cat=JN008"

	# Variable for storing feed content
	rss_content = ""

	# Read the feed into rss_content
	open(rss_feed) do |f|
	   rss_content = f.read
	end
	rss = RSS::Parser.parse(rss_content, false)
	@feed = rss
	
	@jobitems = Job.all
	
	@jobs = Job.all
	@sarr = Array.new
	@jobitems.each do |job|
		 @sarr.push(job.source)
	end 
	
	
	
	
  end
  
  def links
	  #### your code goes here #####
	  mysource = Job.find(params[:topsource])
	  @joburl = mysource.url
	  
	  #myjob = Job.find(:all, :conditions => ["source = ?", mysource])
	  #myjob.nil?
	  #@sourcelink = myjob[0].url

		# What feed are we parsing?
		rss_feed = @joburl.to_s

		# Variable for storing feed content
		rss_content = ""

		# Read the feed into rss_content
		open(rss_feed) do |f|
		   rss_content = f.read
		end
		rss = RSS::Parser.parse(rss_content, false)
		@feed = rss
		
		
			
	  respond_to do |format|
	  format.js { render :layout => false}
	  format.html 
	  end
  end

  def index
  
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/jobs/_form.html.erb
<%= form_for(@job) do |f| %>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% @job.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :source %><br />
    <%= f.text_field :source %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<h1>Editing job</h1>

<%= render 'form' %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
<h1>Listing jobs</h1>

<table>
  <tr>
    <th>Source</th>
    <th>Url</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @jobs.each do |job| %>
  <tr>
    <td><%= job.source %></td>
    <td><%= job.url %></td>
    <td><%= link_to 'Show', job %></td>
    <td><%= link_to 'Edit', edit_job_path(job) %></td>
    <td><%= link_to 'Destroy', job, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Job', new_job_path %>

app/views/jobs/new.html.erb
<h1>New job</h1>

<%= render 'form' %>

<%= link_to 'Back', jobs_path %>

app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Source:</b>
  <%= @job.source %>
</p>

<p>
  <b>Url:</b>
  <%= @job.url %>
</p>


<%= link_to 'Edit', edit_job_path(@job) %> |
<%= link_to 'Back', jobs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CoolRSSJobApp</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/main/index.html.erb
<h1>Main#index</h1>
<p>Find me in app/views/main/index.html.erb</p>

app/views/main/links.html.erb
<h1>Main#index</h1>
<p><%=@joburl%></p>

app/views/main/links.js.erb
$("#time_div").html("Jobs from <%=@feed.channel.title %><ul>");
<% @feed.items.each do |job| %>
		 $("#time_div").append(" <li><a href='<%=job.link%>'><%=job.title%></a> </li>");
<% end %>
$("#time_div").append("</ul>");










app/views/main/welcome.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ruby on Rails: Welcome aboard</title>
    <style type="text/css" media="screen">
      body {
        margin: 0;
        margin-bottom: 25px;
        padding: 0;
        background-color: #f0f0f0;
        font-family: "Lucida Grande", "Bitstream Vera Sans", "Verdana";
        font-size: 13px;
        color: #333;
      }

      h1 {
        font-size: 28px;
        color: #000;
      }

      a  {color: #03c}
      a:hover {
        background-color: #03c;
        color: white;
        text-decoration: none;
      }


      #page {
        background-color: #f0f0f0;
        width: 850px;
        margin: 0;
        margin-left: auto;
        margin-right: auto;
      }

      #content {
        float: left;
        background-color: white;
        border: 3px solid #aaa;
        border-top: none;
        padding: 25px;
        width: 600px;
      }

      #sidebar {
        float: right;
        width: 175px;
      }

      #footer {
        clear: both;
      }

      #header, #about, #getting-started {
        padding-left: 75px;
        padding-right: 30px;
      }


      #header {
        background-image: url("/assets/job4.jpg");
        background-repeat: no-repeat;
        background-position: top left;
		text-align: left;
		
        height: 220px;
      }
	 
	  
      #header h1, #header h2 {margin: 0; text-align: right;}
      #header h2 {
        color: #888;
        font-weight: normal;
        font-size: 16px;
		
      }


      #about h3 {
        margin: 0;
        margin-bottom: 10px;
        font-size: 14px;
		text-align: right;
      }

      #about-content {
        background-color: #ffd;
        border: 1px solid #fc0;
        margin-left: -55px;
        margin-right: -10px;
      }
      #about-content table {
        margin-top: 10px;
        margin-bottom: 10px;
        font-size: 11px;
        border-collapse: collapse;
      }
      #about-content td {
        padding: 10px;
        padding-top: 3px;
        padding-bottom: 3px;
      }
      #about-content td.name  {color: #555}
      #about-content td.value {color: #000}

      #about-content ul {
        padding: 0;
        list-style-type: none;
      }

      #about-content.failure {
        background-color: #fcc;
        border: 1px solid #f00;
      }
      #about-content.failure p {
        margin: 0;
        padding: 10px;
      }


      #getting-started {
        border-top: 1px solid #ccc;
        margin-top: 25px;
        padding-top: 15px;
      }
      #getting-started h1 {
        margin: 0;
        font-size: 20px;
      }
      #getting-started h2 {
        margin: 0;
        font-size: 14px;
        font-weight: normal;
        color: #333;
        margin-bottom: 25px;
      }
      #getting-started ol {
        margin-left: 0;
        padding-left: 0;
      }
      #getting-started li {
        font-size: 12px;
        color: #888;
        margin-bottom: 25px;
      }
      #getting-started li h2 {
        margin: 0;
        font-weight: normal;
        font-size: 12px;
        color: #333;
      }
      #getting-started li p {
        color: #555;
        font-size: 13px;
      }


      #sidebar ul {
        margin-left: 0;
        padding-left: 0;
      }
      #sidebar ul h3 {
        margin-top: 25px;
        font-size: 16px;
        padding-bottom: 10px;
        border-bottom: 1px solid #ccc;
      }
      #sidebar li {
        list-style-type: none;
      }
      #sidebar ul.links li {
        margin-bottom: 5px;
      }

      .filename {
        font-style: italic;
      }
    </style>
    <script type="text/javascript">
      function about() {
		sor = document.getElementById('source').value;
        info = document.getElementById('links');
        if (window.XMLHttpRequest)
          { xhr = new XMLHttpRequest(); }
        else
          { xhr = new ActiveXObject("Microsoft.XMLHTTP"); }
        xhr.open("GET","/getlinks",true);
        xhr.send('source='+sor);
        info.innerHTML = xhr.responseXML;
        info.style.display = 'block'
      }
	  
    </script>
	<%= javascript_include_tag "prototype" %>
	<%= javascript_include_tag :defaults %>
	  </head>
  <body>
    <div id="page">
      <div id="sidebar">
        <ul id="sidebar-items">
          <li>
            <h3>Some popular Job sites</h3>
            <ul class="links">
              <li><a href="http://www.aftercollege.com/">After College</a></li>
              <li><a href="http://www.bestjobsusa.com/">Best Jobs in US</a></li>
              <li><a href="http://www.careerbuilder.com/">Career Builder</a></li>
            </ul>
          </li>
        </ul>
      </div>

      <div id="content">
	  
        <div id="header">		
		<h1><br><br><br><br><h1>
          <h1>Welcome to the Job Seeker Application</h1>
		  <br>
		  <h2>   Powered by Ruby on Rails!</h2>
        </div>

		<br>
		<br>
        <div id="about">
          <h3><a href="rails/info/properties" onclick="about(); return false">About this  application </a></h3>
          <div id="about-content" style="display: none"></div>
        </div>
		

			  <table>
			  <% for job in @jobs %>
					<tr>
					  <td><%= job.source %>					  
					  <%= link_to "-->Get Job Links", { :controller => "main", :action => "links", :topsource=>job }, :remote => true  %></td>
					</tr>
				  <% end %>
			</table>
			
			<h5><div id='time_div'> </div></h5>
			<div id="getting-started">
			 <ol>
            <li>
              <a href ='/jobsearch'> Search Jobs Now!</a>
              <p>To see RSS feeds from vairous job sources.</p>
            </li>

            <li>
              <a href ='/sources'>Update Your job Sources</a>
              <p>Add, remove or update job sources</span>.</p>
            </li>
            
          </ol>
        </div>
      </div>

      <div id="footer">&nbsp;</div>
    </div>
  </body>
</html>


<p></p>
We currently have <%= @source %> sources.